### ISSUE TITLE
Fehlermeldung bei Ausführung

### ISSUE THREAD

**Issue by evrehf** [Daywalker7754/Generosity#1]
Unabhängig von der Konfiguration folgt folgender Fehler. Habe ich etwas übersehen?

File "Main.py", line 17, in <module>
File "ConfigHandler.py", line 49, in get_statement_of_funds_name
UnboundLocalError: local variable 'name' referenced before assignment
[588] Failed to execute script 'Main' due to unhandled exception!

**Comment by Daywalker7754** [comment]
Hallo, das ist ein gängiger Fehler wenn die Datei nicht aus dem Hauptordner gestartet wird. Bitte der Anleitung wie in der Readme folgen, wichtig hierbei die Main.Exe aus dem Hauptordner starten und nicht aus dem Main Ordner

- Öffnen der Eingabenaufforderung in dem Hauptordner
- Ausführen des Befehls .\dist\Main\Main.exe in der Eingabeaufforderung

**Comment by evrehf** [comment]
Darf ich fragen mit welcher FiBu Software Du die Ergebnisse verarbeitest?

**Comment by evrehf** [comment]
hat funktioniert. Vielen Dank für die schnelle Reaktion und Lösung! Hatte diesen Schritt in der Anleitung missverstanden.

**Comment by evrehf** [comment]
hat funktioniert. Vielen Dank für die schnelle Reaktion und Lösung! Hatte diesen Schritt in der Anleitung missverstanden.

**Comment by Daywalker7754** [comment]
> Darf ich fragen mit welcher FiBu Software Du die Ergebnisse verarbeitest?

MS Buchhalter
