### ISSUE TITLE
Art der Gewinnermittlung FIFO / LIFO

### ISSUE THREAD

**Issue by christianfuerst** [Daywalker7754/Generosity#2]
Servus, mal eine Frage zur Gewinnermittlung von Generosity:
Wenn ich den Code richtig interpretiere, kommt bei der Gewinnermittlung die FIFO Methode zum Einsatz.
Ist ggf. auch Support für die LIFO Methode geplant, da diese von den Finanzämtern für die Steuerbilanz zwingend gefordert wird?

**Comment by arnolde** [comment]
@christianfuerst Ist das wirklich so? Hast Du dafür eine Quelle? Ich beginne mich gerade in das Thema einzuarbeiten und war bisher der Meinung, FIFO sei anzuwenden.

**Comment by christianfuerst** [comment]
Hi @arnolde Das ist soweit ich verstanden habe in [§ 6 Abs. 1 Nr. 2a EStG](https://www.haufe.de/finance/haufe-finance-office-premium/einkommensteuergesetz-6-bewertung_idesk_PI20354_HI43516.html) geregelt.

Bin über diese Quellen darauf gekommen:
- https://www.haufe.de/finance/haufe-finance-office-premium/wertpapiere-nach-hgb-estg-und-ifrs-4143-verbrauchsfolgeverfahren_idesk_PI20354_HI1100637.html
- https://www.juhn.com/fachwissen/gmbh-steuerrecht/vermoegensverwaltende-gmbh-mit-aktien/

Habe mittlerweile die ersten Jahresabschluss mit Aktien/Optionen innerhalb der GmbH hinter mir und trotz Anwendung von FIFO so vom Finanzamt durch gewunken. Mache vorerst so weiter und würde das Issue hier erst einmal wieder zu machen.
